#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///tobacco?serverTimezone=GMT
    username: root
    password: root
#  mvc:
#    view:
#      prefix: /webapp/WEB-INF/jsp/
#      suffix: .jsp
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
  aop:
    proxy-target-class: false


#mybatis
mybatis:
  type-aliases-package: com.rst.pojo
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mappers/*.xml

#lOG
logging:
  level:
    com.cy: DEBUG
